# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.version.version)

1.19.1


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
a = np.arange(10)
print('The size in memory is %d' % (a.size * a.itemsize))

The size in memory is 80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
%system python -c 'import numpy as np; np.info(np.add)'

["add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])",
 '',
 'Add arguments element-wise.',
 '',
 'Parameters',
 '----------',
 'x1, x2 : array_like',
 '    The arrays to be added.',
 '    If ``x1.shape != x2.shape``, they must be broadcastable to a common',
 '    shape (which becomes the shape of the output).',
 'out : ndarray, None, or tuple of ndarray and None, optional',
 '    A location into which the result is stored. If provided, it must have',
 '    a shape that the inputs broadcast to. If not provided or None,',
 '    a freshly-allocated array is returned. A tuple (possible only as a',
 '    keyword argument) must have length equal to the number of outputs.',
 'where : array_like, optional',
 '    This condition is broadcast over the input. At locations where the',
 '    condition is True, the `out` array will be set to the ufunc result.',
 '    Elsewhere, the `out` array will retain its original value.',
 '    

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
v = np.zeros(10)
v[4] = 1
print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
v = np.arange(10, 50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
print(v[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
M = np.arange(9).reshape((3, 3))
print(M)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
v = np.array([1, 2, 0, 0, 4, 0])
print(np.where(v > 0)) #forma 1
np.nonzero(v) #forma 2

(array([0, 1, 4]),)


(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
M = np.eye(3)
print(M)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.seed(1988)
v = np.random.random(27)
print(v.reshape((3, 3, 3)))


[[[0.38409659 0.22615207 0.16595481]
  [0.72766105 0.23926443 0.61450854]
  [0.39810529 0.79631857 0.17344196]]

 [[0.44395701 0.50121737 0.5604858 ]
  [0.33129964 0.00232666 0.77589359]
  [0.06966717 0.88159693 0.5791237 ]]

 [[0.50829327 0.88067389 0.03169974]
  [0.67319919 0.26979999 0.69370529]
  [0.20654897 0.72794078 0.50073619]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
M = np.random.random((10, 10))
print('The minimun value is %f and the maximun value is %f' % (M.min(), M.max()))

The minimun value is 0.005037 and the maximun value is 0.997378


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
v = np.random.random(30)
print(np.mean(v))

0.4023752542486421


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [36]:
M1 = np.ones((3, 6))
rows = M1.shape[0]
columns = M1.shape[1]
M1[1:rows-1, 1:columns-1] = 0
print(M1)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [71]:
A = np.ones((3, 6))

Z = np.zeros((A.shape[0] + 2, A.shape[1] + 2))

Z[1:-1, 1:-1] = A

print(Z)




[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [79]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
0.3 == 3 * 0.1

nan
False
False
nan
True


False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [98]:
M = np.diag([1, 2, 3, 4], -1)
print(M)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [123]:
M = np.zeros((8,8))
M[::2, ::2] = 1
M[1::2, 1::2] = 1
print(M)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


###### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [146]:
np.unravel_index(99, (6, 7, 8), order='C')

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [150]:
np.tile(np.eye(2), (4, 4))

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [158]:
np.random.seed(1988)
A = np.random.random((5, 5))
A_norm = (A - np.mean(A)) / np.std(A)
print(A_norm)

[[-0.23302138 -0.83339014 -1.06220817  1.07291422 -0.78354825]
 [ 0.64280602 -0.1797724   1.33389089 -1.03374849 -0.00548372]
 [ 0.21217077  0.4374582  -0.43370983 -1.68418122  1.25625273]
 [-1.42821069  1.65804562  0.50830342  0.23906722  1.65453702]
 [-1.5725301   0.86589722 -0.66747843  0.94384372 -0.90790421]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [164]:
color = np.dtype([('r', np.ubyte, 1), ('g', np.ubyte, 1), ('b', np.ubyte, 1), ('a', np.ubyte, 1)])

<ipython-input-164-49b4bf25a489>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([('r', np.ubyte, 1), ('g', np.ubyte, 1), ('b', np.ubyte, 1), ('a', np.ubyte, 1)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [170]:
M1 = np.arange(15).reshape(5, 3)
M2 = np.arange(6).reshape(3,2)
print(M1.dot(M2))

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [15]:
v = np.arange(20)
v[(v > 3) & (v < 8)] = -1
v


array([ 0,  1,  2,  3, -1, -1, -1, -1,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [24]:
import numpy as np

In [3]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [5]:
z = np.arange(10)

In [6]:
z**z

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

In [7]:
2 << z >> 2

array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256])

In [8]:
z <- z

array([False, False, False, False, False, False, False, False, False,
       False])

In [9]:
1j * z 

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+7.j,
       0.+8.j, 0.+9.j])

In [10]:
z/1/1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [13]:
# not legal z<z>z

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [14]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-14-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-14-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [28]:
Z = np.random.uniform(-10, 10, (10,5))
np.copysign(np.ceil(np.abs(Z)), Z)

array([[ -6.,   3.,   6.,  -6.,  -3.],
       [  4.,  -8.,  -5.,   4.,  -3.],
       [  8.,   8.,  -8.,   2.,   2.],
       [ -8., -10.,   3.,  10.,  -7.],
       [  3.,   4.,   2.,  -8.,   4.],
       [  1.,  -8.,   6.,  -8.,  -7.],
       [  5.,   5.,   5.,   6.,  -4.],
       [ -7.,  -6.,   2.,  -5.,   6.],
       [ 10.,  -7.,  -6.,   7.,   8.],
       [ -1.,   4.,   4.,  -1.,   3.]])

#### 30. How to find common values between two arrays? (★☆☆)

In [34]:
a = np.array([1, 2, 9, 4])
b = np.array([3, 5, 1, 9])
np.intersect1d(a, b)

array([1, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [4]:
defaults = np.seterr(all='ignore')

In [5]:
np.array([1, 1])/0

array([inf, inf])

In [6]:
defaults = np.seterr(**defaults)

In [7]:
np.array([1, 1])/0

<ipython-input-7-b545fd62a7e2>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([1, 1])/0


array([inf, inf])

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [8]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-8-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [18]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)

In [19]:
print(yesterday)
print(today)
print(tomorrow)

2020-08-18
2020-08-19
2020-08-20


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [10]:
np.arange('2016-07', '20160-08', dtype='datetime64[D]')

array([ '2016-07-01',  '2016-07-02',  '2016-07-03', ..., '20160-07-29',
       '20160-07-30', '20160-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [19]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [33]:
M = np.random.uniform(0, 30, (5, 5))
M1 = np.trunc(M)
M2 = np.floor(M)
M3 = M.astype('int')
M4 = M // 1
print(M1)
print(M2)
print(M3)
print(M4)

[[12. 24. 19.  0. 10.]
 [ 4. 15. 11. 18. 10.]
 [10. 19.  3. 19.  8.]
 [15.  1.  0. 16. 10.]
 [28. 11. 20.  5.  2.]]
[[12. 24. 19.  0. 10.]
 [ 4. 15. 11. 18. 10.]
 [10. 19.  3. 19.  8.]
 [15.  1.  0. 16. 10.]
 [28. 11. 20.  5.  2.]]
[[12 24 19  0 10]
 [ 4 15 11 18 10]
 [10 19  3 19  8]
 [15  1  0 16 10]
 [28 11 20  5  2]]
[[12. 24. 19.  0. 10.]
 [ 4. 15. 11. 18. 10.]
 [10. 19.  3. 19.  8.]
 [15.  1.  0. 16. 10.]
 [28. 11. 20.  5.  2.]]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [40]:
M = np.zeros((5, 5))
print(M + np.arange(5))

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [8]:
generator = ((x + 1) * 2 for x in range(10))
np.fromiter(generator, int)


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [15]:
x = np.linspace(0, 1, 11, endpoint=False)
x = x[x > 0]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [25]:
x = np.random.random(10)
x.sort()
print(x)

[0.01940023 0.06939952 0.31317564 0.34938441 0.35086635 0.46015143
 0.55086694 0.70411406 0.74088956 0.8866392 ]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [31]:
x = np.arange(10000)
print(np.add.reduce(x))

49995000


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [39]:
A = np.random.random((5, 5))
B = np.random.random((5, 5))
np.array_equal(A, B)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [46]:
w = np.arange(10)
w.flags.writeable = False
w[1] = 10

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [63]:
M = np.random.uniform(-10, 10, (10,2))
P = np.zeros((10, 2))
for r in range(M.shape[0]):
    P[r, 0] = np.sqrt(M[r, 0]**2 + M[r, 1]**2)
    P[r, 1] = np.arctan2(M[r, 1], M[r, 0])
print(M)
print(P)

[[-5.04510762  9.50601041]
 [-2.39380185  1.9669663 ]
 [-4.12773984 -2.58482193]
 [ 8.5315891  -5.78573179]
 [-6.73517024 -3.57135514]
 [ 1.68096178 -3.18404827]
 [ 1.5849381  -8.40385302]
 [-8.45728741 -8.37501912]
 [ 6.02242252  1.14093546]
 [-1.07793325  5.59681469]]
[[10.76184672  2.05872323]
 [ 3.09826463  2.4537645 ]
 [ 4.8702711  -2.58212545]
 [10.30838033 -0.59591331]
 [ 7.62345693 -2.65403531]
 [ 3.60052717 -1.08505342]
 [ 8.55200412 -1.38438923]
 [11.90238025 -2.36108197]
 [ 6.12954376  0.18722905]
 [ 5.69967322  1.7610642 ]]


In [65]:
#forma simple
M = np.random.random((10, 2))
X, Y = M[:, 0], M[:, 1]
mod = np.sqrt(X**2 + Y**2)
ang = np.arctan2(Y, X)
print(mod)
print(ang)

[0.81842966 0.5534498  0.54369873 1.01804414 0.78774432 0.63989215
 0.91712375 0.27687392 0.9693181  0.6028743 ]
[0.19730504 1.31848582 1.24687164 1.27576275 1.51868768 1.57028945
 0.08479984 0.56202479 0.93428966 1.16187244]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [7]:
v = np.random.random(10)
v

array([0.93887941, 0.80136505, 0.23577594, 0.09146888, 0.96102682,
       0.11968705, 0.38020104, 0.56318639, 0.80602532, 0.08330852])

In [8]:
v[v == v.max()] = 0

In [9]:
v

array([0.93887941, 0.80136505, 0.23577594, 0.09146888, 0.        ,
       0.11968705, 0.38020104, 0.56318639, 0.80602532, 0.08330852])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [15]:
#Copia de la respuesta
Z  = np.zeros((5, 5), [('x', float), ('y', float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [25]:
X = np.random.randint(1, 9, size = (6, 6))
Y = np.random.randint(10, 50, size=(6, 6))
X, Y

(array([[4, 3, 1, 7, 4, 3],
        [5, 5, 2, 2, 8, 3],
        [1, 4, 4, 7, 4, 7],
        [8, 4, 5, 8, 5, 5],
        [6, 4, 7, 4, 8, 6],
        [5, 6, 4, 1, 8, 7]]),
 array([[37, 26, 42, 47, 38, 37],
        [19, 34, 10, 26, 23, 35],
        [47, 16, 37, 12, 26, 22],
        [28, 13, 46, 27, 44, 18],
        [15, 27, 15, 13, 30, 42],
        [20, 34, 36, 44, 21, 26]]))

In [27]:
C = 1 / (X - Y)
C

array([[-0.03030303, -0.04347826, -0.02439024, -0.025     , -0.02941176,
        -0.02941176],
       [-0.07142857, -0.03448276, -0.125     , -0.04166667, -0.06666667,
        -0.03125   ],
       [-0.02173913, -0.08333333, -0.03030303, -0.2       , -0.04545455,
        -0.06666667],
       [-0.05      , -0.11111111, -0.02439024, -0.05263158, -0.02564103,
        -0.07692308],
       [-0.11111111, -0.04347826, -0.125     , -0.11111111, -0.04545455,
        -0.02777778],
       [-0.06666667, -0.03571429, -0.03125   , -0.02325581, -0.07692308,
        -0.05263158]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [42]:
for dtype in [np.int8, np.int16, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float16, np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-32768
32767
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-65500.0
65500.0
0.000977
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [49]:
v = np.arange(1000)
print(v)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [50]:
#Copia de respuesta
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [58]:
#copia respuesta
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

10


In [59]:
Z, v

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
 9.700216076226976)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)